### ISSUE TITLE
[ISSUE] Flac input

### ISSUE THREAD

**Issue by afonya2** [MCJack123/AUKit#4]
1. When you trying to input a function(): string into the aukit.stream.wav() it works but if you try to input a function(): string into the aukit.stream.flac() it just says it requires string, but the guide says it accepts function(): string,

![image](https://user-images.githubusercontent.com/64413731/231437107-844c0388-c2f9-49b8-a931-31b05e31b156.png)

Code:
```lua
local aukit = require("aukit")
local dta = http.get({url = "<A github link to a flac file>", binary = true})
local lines = {}
local block = 48000
while true do
  local chunk = dta.read(block)
  if not chunk then break end
  table.insert(lines,chunk)
end

local pos = 0
function catter()
  pos = pos + 1
  return lines[pos]
end

aukit.play(aukit.stream.flac(catter), peripheral.wrap("left"), peripheral.wrap("right"))
```

2. When i input the string from the table lines then its just lagging

**Comment by MCJack123** [comment]
The second issue is because FLAC decoding is *extremely* slow; I don't recommend using it anywhere unless you really need it, or you're using CraftOS-PC Accelerated.
