### ISSUE TITLE
can you stream from http?

### ISSUE THREAD

**Issue by dolphin-cat** [MCJack123/AUKit#5]
i have an azuracast instance that hosts an mp3 file with icecast on https://\<serverid\>.contaboserver.net:\<stationport\>/radio.mp3 azuracast devs also host a public demo on https://demo.azuracast.com/listen/azuratest_radio/radio.mp3 can i stream the file live?

**Comment by MCJack123** [comment]
You cannot stream MP3 files using AUKit, as it is not [one of the supported formats](https://github.com/MCJack123/AUKit#supported-audio-formats). However, you can use the [`austream`](https://github.com/MCJack123/AUKit#austreamauplay) program to stream any of the supported formats.

**Comment by dolphin-cat** [comment]
azuracast icecast2 allows you to make a flac 32kbps mount, so i made one. when i try it it hangs for a while and then exits with response is too large
